### ISSUE TITLE
Need clarification on STIG checklist versus these images

### ISSUE THREAD

**Issue by ferrx** [plus3it/spel#116]
Hi, I just spun up the RHEL 7 stig'd image on AWS (ami-6ba9250a) and I'm just randomly checking some of the checklist items found in the "Red Hat Enterprise Linux 7 Security Technical Implementation Guide" and so far the random check is coming back falsely. Is this what is meant by "**NOT HARDENED**" in the AMI description? If so, I might be missing what it is meant by this being STIG'd.

Checklist is here https://people.redhat.com/swells/scap-security-guide/tables/table-rhel7-stig.html and can be viewed from nist.gov here https://nvd.nist.gov/ncp/checklist/796

Some examples,
1) **RHEL-07-010140**, _"When passwords are changed or new passwords are assigned, the new password must contain at least one numeric character." ".... Modify the dcredit setting in /etc/security/pwquality.conf to require the use of a digit in passwords. "_ Checking pwquality.conf shows everything is commented out.

2) **RHEL-07-010050**, _"The operating system must display the Standard Mandatory DoD Notice and Consent Banner before granting local or remote access to the system via a command line user logon." "To configure the system login banner edit /etc/issue..."_ I don't see a login banner and issue does not contain the appropriate login banner text.

Can someone point me in the right direction? My assumption at this point is that these AMIs are there to support me to more easily apply the NIST checklist, so that I can go in and personally set things such as the pwquality.conf file.. is that assumption correct?

**Comment by ferricoxide** [comment]
From the project's README.md:

~~~
STIG-Partitioned Enterprise Linux (spel) is a project that helps create and publish Enterprise Linux
images that are partitioned according to the DISA STIG. The resulting images also use LVM to
simplify volume management. The images are configured with help from the scripts and packages
in the AMIgen6, AMIgen7, and Lx-GetAMI-Utils projects.
~~~

What this means is that the resultant AMI is _partitioned_ to meet STIG requirements around partitioning. Beyond that, no STIG-hardening is done. If you review the mentioned projects' ([AMIgen6](https://github.com/ferricoxide/AMIgen6.git) and [AMIgen7](https://github.com/ferricoxide/AMIgen7.git)) contents, you'll see that, but for the STIG-compatible _partitioning_, the AMIs just implement a generic, `@Core`-style build that is supplemented with the tools necessary to function correctly within an AWS context (specifically, necessary utilities to process UserData and leverage CloudFormation's bootstrapping capabilities).

If you wish to harden the instances launched from these AMIs, we publish a separate tool for that called [Watchmaker](https://github.com/plus3it/watchmaker.git). Typically, users of our AMIs invoke watchmaker either via UserData or CloudFormation's bootstrapping capabilities (see [watchmaker's documentation](http://watchmaker.readthedocs.io) for guidance).

**Comment by ferrx** [comment]
Thanks, that's extremely helpful.

I will look into Watchmaker as a solution for hardening. Right now I'm a little confused by the approach for usage, and maybe this belongs on watchmaker's issues, but the recommended installation for watchmaker is `pip install watchmaker` but pip does not work with FIPS on. Maybe I need to build from source? Should I just post an issue on watchmaker?

**Comment by lorengordon** [comment]
@ferrx `pip` actually works just fine in FIPS mode. You just need to point to the pypi index server that is serving sha256 hashes. We have examples in the watchmaker "usage" documentation, https://watchmaker.readthedocs.io/en/stable/usage.html#watchmaker-as-ec2-userdata.

**Comment by ferricoxide** [comment]
### spel Notes:

No worries. I'm going to update the README, this week, to try to stress the difference between "STIG-ready partitioning" and "STIG-hardened".

We'd chosen to not harden the AMI - using Watchmaker to handle things at launch-time - because we have different customers that use different STIG-profiles. Managing _one_ AMI plus a profile-based hardener was a lot more manageable than maintaining a bajillion AMIs per month. The latter would have required maintaining:

`( 1 CentOS 6 HVM AMI + 1 CentOS 7 HVM AMI + 1 RHEL 6 HVM AMI + 1 RHEL 7 HVM AMI ) x 5 Regions x N STIG Profiles x 12 months`

Worth of AMIs.

### watchmaker Notes:

As to the watchmaker issue you mention, yes, with FIPS mode on, `pip` doesn't work "out of the box". This is due to how Red Hat maintains their `pip` package. We opened a bug with them a _number_ of months ago on that issue. To date it's not been remediated. We're hoping that, maybe by the time 7.5 drops, they'll have fixed it.

Unless/until Red Hat fixes their FIPS package, you can force the `pip` utility to use FIPS-compatible indexes. I _think_ we have the "how" addressed in the watchmaker dox. That said, the method is to use `pip install -i  https://pypi.org/simple --upgrade pip setuptools watchmaker`.

**Comment by ferrx** [comment]
I see, that would be a maintenance nightmare for sure.

Thanks for the clarification. I was able to work around the pip/fips problem and ran watchmaker successfully in my instance. Hopefully RH gets that sorted.. it's not the first time I've run into FIPS non-compliance with tools I want to install.. like Gitlab.

**Comment by ferricoxide** [comment]
Red Hat isn't the only one. We've run into it with several of our CI tools. Everyone still seems to do MD5 first and SHA-2 as not much more than an afterthought.
