### ISSUE TITLE
/tmp tmpfs

### ISSUE THREAD

**Issue by mgresko** [plus3it/spel#117]
Not the correct place to put this but...

@ferricoxide  how did you end up handling nodev, noexec, nosuid for /tmp for STIG hardening?
https://access.redhat.com/discussions/2918031

**Comment by ferricoxide** [comment]
We never explicitly addressed it as there wasn't a good method for doing so (due the bugaboos mentioned in the RHN thread). That said, because our hardening framework leverages the STIG defaults for linking `/tmp` and `/var/tmp`, the attributes applied to `/var/tmp` back-propagate those settings demanded for _it_ up `/tmp`.

So, while this has the side effect of taking care of making the attributes present on `/tmp`, it also means the contents of `/var/tmp` won't persist across reboots. People expecting/requiring `/var/tmp`'s contents to persist across boots are apt have problems with these STIG controls. No one's filed an issue related to lack of `/var/tmp` content-persistence, so there's been no priority to revisit the issue.

 I know that, typically, stuff placed in `/etc/systemd` supersedes stuff set in `/usr/lib/systemd`. However never tested for any bugaboos (again, a "time constraints and lack of community response" thing).

**Comment by mgresko** [comment]
@ferricoxide thank you for the help here!  Am I understanding correctly that as part of your hardening your are you are doing something like `/tmp /var/tmp none rw,noexec,nosuid,nodev,bind 0 0` in `/etc/fstab`?  For me I don't see tmp content-persistence being an issue at all.

**Comment by ferricoxide** [comment]
Correct. _Within the spel-created images_ we do nothing to establish the bind-mount of `/tmp` to `/var/tmp`.

If that happens at all, it happens as a result of running a hardening-framework (like [watchmaker](https://github.com/plus3it/watchmaker.git)) against the instance launched from the image.

**Comment by mgresko** [comment]
@ferricoxide thanks.  I am going to check out watchmaker.. been using ansible to do the hardening and it has been painful to say the least.
