### ISSUE TITLE
kickstart not used for 7.x builds?

### ISSUE THREAD

**Issue by rpostgate** [plus3it/spel#129]
Apologies, not really an issue, and this may be more of an amigen7 question than specifically for 'spel'...

Why does the 6.x/amigen6 build seem to make use of a kickstart file to do a bunch of setup, in particular the partitioning, whereas the 7.x/amigen7 build instead uses DiskSetup.sh? Kickstart seems like a nice clean way to handle a lot of details, so I was wondering why it was ditched for amigen7.

(I should note that I am not actually that interested in the 6.x build process by itself - I am only working with 7.x on AWS at this time. I may experiment with 7.x builds for other platforms later.)

Thank you to all the contributors on this and amigen6/7! It's obvious that a lot of work went in to these, and it is much appreciated.

**Comment by ferricoxide** [comment]
KickStart is used for neither. Both just use a `yum install` to a chroot(). =)

**Comment by lorengordon** [comment]
Hi @rpostgate, the AWS AMI builds (based on AMIGen6/7) do not use kickstart and never have.

spel _does_ contain a kickstart file used for the [centos6 virtualbox/vagrant build](https://github.com/plus3it/spel/blob/develop/spel/minimal-linux.json#L50-L76). Currently spel does not offer a similar centos7 virtualbox/vagrant build, which is why there is no corresponding kickstart for centos7. There is an issue already for creating such a build. If you'd like to give it a go, PRs are welcome! 😁

**Comment by rpostgate** [comment]
Oh, I didn't see a DiskSetup.sh in the amigen6 package, so I assumed the spel/kickstarts/ks.centos6.minimal.cfg file and the partitioning within were being used for 6.x (on everything). Thank you for the clarification guys!

**Comment by lorengordon** [comment]
Ahhhh yes, I believe the equivalent script is CarveEBS.sh in AMIGen6. You can compare the scripts amigen6-build.sh and amigen7-build.sh to get a better understanding of the workflow in each.

https://github.com/plus3it/spel/tree/develop/spel/scripts

I'll close the issue, but feel free to reopen if there's more to address.
