### ISSUE TITLE
extend LVM partition 

### ISSUE THREAD

**Issue by rbaker5137** [plus3it/spel#138]
How do I extend the LVM partition?

**Comment by ferricoxide** [comment]
Your question isn't immediately clear. Can you provide more context - say, detail a use-case you were looking to meet that your currently not able to (inclusive of whether you're looking for EL6 or EL7 usage).

**Comment by robertcurcio** [comment]
If you need to resize a volume in the volume group do this:

1) Take a snapshot of the root EBS volume to extend. Record the volume
identifier

2) Once the snapshot completes, create a new volume from the snapshot with
the full size you want to extend it to. For example, your original snapshot
and volume is 50GB, you may want the new volume to be 100GB.

3) Unmount the old volume from the instance.

4) Attach the new volume to the throwaway instance.

5) vgdisplay (look for the VG name - which is VolGroup00)

6) vgchange -an VolGroup00 (to disable the volume group)

7) pvdisplay (look for the PV name - in this example it's /dev/sdf2)

8) pvchange -u /dev/sdf2 (to change the UUID)

9) pvresize /dev/sdf2

10) pvdisplay (should show new larger size)

11) vgdisplay (should now show the volume group reflecting the new 150GB
size)

12) lvdisplay (look for the LV name of the root - I used
/dev/VolGroup00/rootVol)

13) lvextend -l +100%FREE /dev/VolGroup00/rootVol or lvextend -L+4GB
/dev/VolGroup00/rootVol

14) vgchange -u VolGroup00 (to change the UUID)

15) vgchange -ay (to activate the volume group)

attach back to the origional instance as /dev/sda1


xvdf                    202:80   0   250G  0 disk
├─xvdf2                 202:82   0 149.5G  0 part
│ ├─VolGroup00-swapVol  253:1    0     2G  0 lvm
│ ├─VolGroup00-logVol   253:4    0     2G  0 lvm
│ ├─VolGroup00-homeVol  253:2    0     1G  0 lvm
│ ├─VolGroup00-rootVol  253:0    0   134G  0 lvm
│ ├─VolGroup00-auditVol 253:5    0   8.5G  0 lvm
│ └─VolGroup00-varVol   253:3    0     2G  0 lvm

**Comment by ferricoxide** [comment]
@robertcurcio I would probably advise against the method cited.

While it's one of several ways one could increase the root VG's number of PEs, it's very labor-intensive and increases the possible exposure to data-loss. I'd probably only use that method on a (preferably non-production) instance that I couldn't afford to easily rebuild. You'd experience less down-time and expose yourself to lower risk of data-loss by attaching a secondary EBS, growing the root VG onto the new EBS, then extending your LVs with the space from the secondary EBS.

If you _can_ afford to rebuild an instance - or are starting from scratch, any way, you can just launch your instance with a larger-than-default EBS. If using a spel EL7 AMI, you can just add the requisite `lvrsize` operations to your deployment-automation process (`cloud-init`, `cfn-bootstrapper`, etc.). Steps for EL6 require a reboot (due to kernel limitations), but the process is still, otherwise, wholly encapsulatable into an automated-provisioning sequence.

**Comment by ferricoxide** [comment]
Added content to the [FAQ](/plus3it/spel/blob/develop/docs/FAQ.md#q-the-root-volume-group-and-its-partitions-seem-too-small-for-my-use-case-is-there-any-way-i-can-un-handcuff-myself-from-the-current-partitioning-scheme)

**Comment by ferricoxide** [comment]
Been two weeks without further activity on this ticket. Assuming questions have been adequately answered.

**Comment by rbaker5137** [comment]
Yes i was able to successfully resize the LVM volume.
