### ISSUE TITLE
[Feature Request] Support customized partitioning

### ISSUE THREAD

**Issue by ferricoxide** [plus3it/spel#360]
Implement pending completion of plus3it/AMIgen7#76

**Comment by eseglem** [comment]
I had been meaning to ask about something like this. Would it be possible to support auto expansion to fill a given EBS volume size? Like a standard Amazon Linux image does. 

When a system has a large number of dependencies installed through `yum` the current AMIs run out of space fairly quickly, and just being able to up the root EBS volume to 30 or 40G would be enough to get past that part without pain. 

Having to specify the partition sizes would be workable as well, if necessary.

**Comment by lorengordon** [comment]
@eseglem That actually works already, but because the disk is using LVM, you have to run some commands in userdata to take advantage of it. See this article: https://github.com/plus3it/spel/blob/master/docs/LargerThanDefaultRootEBS_EL7.md

**Comment by eseglem** [comment]
Awesome, hadn't seen that link before, that is super helpful. Should be easy enough to add to the userdata in our install scripts.

Personally I think it would be more intuitive for that to actually be the default / automatic behavior. I believe most other images I have encountered automatically expand `/` to fill the volume. And having to add additional userdata to do so is not the behavior I would normally expect.

Now that we know the way to do it though, we can work with it though. And thanks for the quick response, actually came in handy today.

**Comment by jamescassell** [comment]
Personally, I'd split any extra space 25/75 between / and /var, so I'd not be in favor of adding it all to / automatically. This is fine for regular images since there is not usually any partitioning and it's available anywhere on the filesystem hierarchy.

**Comment by lorengordon** [comment]
It is actually an agent/service running on the system that expands the disk at launch, [cloud-init](https://cloudinit.readthedocs.io/en/latest/) on linux or [ec2launch](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch.html) on windows (or ec2config in older versions). The image itself only installs the package. If you would like to develop an agent or feature that implements disk expansion functionality for LVM-partitioned disks, then we could include that package and you would be able to use it with spel. However, such an agent would be completely outside the scope of this project.

Automatic disk expansion works fine when there is a single partition on the raw disk, and so all space gets allocated to the one partition. There is no user-input or decision needed. The concept breaks down when there are multiple partitions on the one disk, and multiple partitions are a core feature of spel images. It is perfectly normal and expected to run sysadmin-type commands in userdata, in order to perform launch-time customizations to meet unique user requirements. There could be some _default_ configuration, with support for user-directives to override the default, e.g. using cloud-init's #cloud-config. Spel could set such a default configuration, but again, the feature itself needs to be provided by a package managed outside this project.

**Comment by ferricoxide** [comment]
> I had been meaning to ask about something like this. Would it be possible to support auto expansion to fill a given EBS volume size? Like a standard Amazon Linux image doe

Best we'd currently be able to do is enable auto-expansion of the _partition that hosts the LVM_. That said, default-enabling the `growpart` wouldn't buy AMI-users that much: AMI-users would still have to take care of then growing the overlying LVMs and filesystems. Basically, default-enabling cloud-init's call to  `growpart` would only eliminate the need to do:

~~~
growpart:
  mode: auto
  devices: [ '/dev/xvda2' ]
  ignore_growroot_disabled: false
~~~

Within a `cloud-init` userData directive-block or the need to do:

~~~
/usr/bin/growpart /dev/xvda 2
~~~

Within a `#!/bin/bash` userData content-block.

Which is to say that, given default-enabling would solve only a very small part of the overall problem and that there has  been little in the way of requests for us to solve that very small part, it made more sense to write the FAQ entries to which Loren previously referred.

**Comment by ferricoxide** [comment]
go codebuild go
