### ISSUE TITLE
Do we really need volgroups ?

### ISSUE THREAD

**Issue by robertcurcio** [plus3it/spel#98]
Do we really need volgroups ?

**Comment by ferricoxide** [comment]
See name of project: "_STIG-Partitioned Enterprise Linux (spel)..._". The STIGs for EL7 specify separate filesystems for `/var`, `/var/log/audit`, `/tmp`, `/home` (or equivalent). The STIGs for EL6 additionally specify a separate filesystem for `/var/log`. Due to explicitly-enumerated partitioning requirements, `/` (rootVol) necessarily must be its own filesystem, as well. This project uses LVM to meet these STIG-specified partitioning requirements.
